// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArt7iTp7IzxXrysmQSAKoYbpMFH0MR-pA',
    appId: '1:310434492180:web:16b07b86e6f4ee32671c01',
    messagingSenderId: '310434492180',
    projectId: 'final-android-project-702af',
    authDomain: 'final-android-project-702af.firebaseapp.com',
    storageBucket: 'final-android-project-702af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRTgxqMuemGexbAM5_X_z3MMr4aMcZlQw',
    appId: '1:310434492180:android:bb555a9f9fec0dbf671c01',
    messagingSenderId: '310434492180',
    projectId: 'final-android-project-702af',
    storageBucket: 'final-android-project-702af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsvDEPUNowJB-RoT_JTihNCIwt9ellKgU',
    appId: '1:310434492180:ios:5a254b24f69d7203671c01',
    messagingSenderId: '310434492180',
    projectId: 'final-android-project-702af',
    storageBucket: 'final-android-project-702af.firebasestorage.app',
    iosBundleId: 'com.example.finalAndroidProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsvDEPUNowJB-RoT_JTihNCIwt9ellKgU',
    appId: '1:310434492180:ios:5a254b24f69d7203671c01',
    messagingSenderId: '310434492180',
    projectId: 'final-android-project-702af',
    storageBucket: 'final-android-project-702af.firebasestorage.app',
    iosBundleId: 'com.example.finalAndroidProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArt7iTp7IzxXrysmQSAKoYbpMFH0MR-pA',
    appId: '1:310434492180:web:bc51b41045b48245671c01',
    messagingSenderId: '310434492180',
    projectId: 'final-android-project-702af',
    authDomain: 'final-android-project-702af.firebaseapp.com',
    storageBucket: 'final-android-project-702af.firebasestorage.app',
  );
}
